#!/bin/bash

WRAPPER_PATH=$(readlink -f /usr/bin/google-chrome)
BASE_PATH="$WRAPPER_PATH-base"
mv "$WRAPPER_PATH" "$BASE_PATH"

cat > "$WRAPPER_PATH" <<_EOF
#!/bin/bash
if [ -z "\${DISPLAY}" -o "\${HEADLESS:-'true'}" == 'true' ]; then
  HEADLESS_ARG='--headless';
fi

# Note: exec -a below is a bashism.
exec -a "\$0" "$BASE_PATH" --no-sandbox "\${HEADLESS_ARG:-''}" "\$@"
_EOF
chmod +x "$WRAPPER_PATH"
